export const SET_PAGE = 'SET_PAGE';

export const REQUEST_POSTDATA_PENDING = 'REQUEST_POSTDATA_PENDING';
export const REQUEST_POSTDATA_SUCCESS = 'REQUEST_POSTDATA_SUCCESS';
export const REQUEST_POSTDATA_FAILED = 'REQUEST_POSTDATA_FAILED';

export const REQUEST_ZIPDATA_PENDING = 'REQUEST_ZIPDATA_PENDING';
export const REQUEST_ZIPDATA_SUCCESS = 'REQUEST_ZIPDATA_SUCCESS';
export const REQUEST_ZIPDATA_FAILED = 'REQUEST_ZIPDATA_FAILED';

export const REQUEST_COUNTRYDATA_PENDING = 'REQUEST_COUNTRYDATA_PENDING';
export const REQUEST_COUNTRYDATA_SUCCESS = 'REQUEST_COUNTRYDATA_SUCCESS';
export const REQUEST_COUNTRYDATA_FAILED = 'REQUEST_COUNTRYDATA_FAILED';