export const SET_PAGE = 'SET_PAGE';

export const REQUEST_POSTDATA_PENDING = 'REQUEST_POSTDATA_PENDING';
export const REQUEST_POSTDATA_SUCCESS = 'REQUEST_POSTDATA_SUCCESS';
export const REQUEST_POSTDATA_FAILED = 'REQUEST_POSTDATA_FAILED';